version: "3"
services:
  mysql:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
  go:
    build: .
    command: ["./wait-for", "mysql:3306", "-t 5000", "--", "./bin/chatapp"]
    depends_on:
      - mysql
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - ${APP_WS_ORIGIN_PORT}:80
    depends_on:
      - go
      - client
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client/:/app
