version: "3"
services:
  mysql:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=asdfasdf88
      - MYSQL_DATABASE=chatapp
      - MYSQL_USER=chatappadmin
      - MYSQL_PASSWORD=asdfasdf88
  go:
    build: .
    command: ["./wait-for", "mysql:3306", "--", "./bin/chatapp"]
    depends_on:
      - mysql
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 8001:80
    depends_on:
      - go
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client/:/app
    ports:
      - 8000:8080
    depends_on:
      - nginx
